on:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'
  workflow_dispatch:

name: CI

jobs:
  test:
    name: Test
    runs-on: macos-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Install lima
        run: brew install lima
      - name: Test template
        run: cd tests && lima direnv exec . hello